version: "3.5"

services:
  node:
    image: invekotin-dev
    container_name: invekotin-dev
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./src:/usr/src/app/src
      - ./package.json:/usr/src/app/package.json
      - type: bind
        source: ./package-lock.json
        target: /usr/src/app/package-lock.json
    ports:
      - 3000:3000
    env_file:
      - .env
    depends_on:
      - mongodb
    command: ["./entrypoint.sh"]

  mongodb:
    image: mongo:5-focal
    container_name: invekotin-mongodb
    env_file:
      - .env
    volumes:
      - mongodb-data:/data/db

volumes:
  mongodb-data:
